version: '3.9'

services:
  liveshorts-front-end:
    container_name: liveshorts-front-end
    image: ghcr.io/bob-park/liveshorts-front-end
    privileged: true
    build:
      context: ./
      dockerfile: ./Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    ports:
      - 3000:3000
